# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "go_api_client/version"

Gem::Specification.new do |s|
  s.name        = "go_api_client"
  s.version     = GoApiClient::VERSION
  s.authors     = ["Nikhil Mungel", "Ketan Padegaonkar", "Shishir Das"]
  s.email       = ["hyfather@gmail.com", "KetanPadegaonkar@gmail.com", "shishir.das@gmail.com"]
  s.homepage    = "https://github.com/ThoughtWorksInc/go-api-client"
  s.summary     = %q{Client to parse Go CI atom feed}
  s.description = %q{This gem parses atom feed generated by the Go Continuous Integration server and provides an OO representation of the pipelines and stages.}

  s.rubyforge_project = "go_api_client"

  s.files         = `git ls-files`.split("\n") - `git ls-files -- vendor/cache`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]

  # specify any dependencies here; for example:
  s.add_development_dependency "webmock"
  s.add_development_dependency "simplecov"
  s.add_development_dependency 'rake'

  s.add_runtime_dependency "nokogiri"
end
